
[general]
	#Any console messages containing any of these strings will be hidden.
	basicFilters = ["Can't keep up!", "Player moved too quickly!"]
	#Any console messages that match any of these regular expressions will be hidden. Uses Java style regex. Backslashes must be escaped, for example use \\s instead of \s to match whitespace.
	regexFilters = [".*Redirecting.*", ".*Exception loading blockstate.*", ".*Failed to parse recipe.*"]

