ServerEvents.tags('item', e => {
    function yearRound(crop){
        e.add('sereneseasons:spring_crops', crop)
        e.add('sereneseasons:summer_crops', crop)
        e.add('sereneseasons:autumn_crops', crop)
        e.add('sereneseasons:winter_crops', crop)
    }

    e.add('sereneseasons:autumn_crops', '/berries_and_cherries:.*grape.*sapling$/')
    e.add('sereneseasons:autumn_crops', 'vintagedelight:ghost_pepper_seeds')
    e.add('sereneseasons:spring_crops', '/berries_and_cherries:.*be.*sapling$/')
    e.add('sereneseasons:spring_crops', 'berries_and_cherries:cherry_tree_sapling')
    e.add('sereneseasons:spring_crops', 'vintagedelight:ghost_pepper_seeds')
    e.add('sereneseasons:spring_crops', 'vintagedelight:oat_seeds')
    e.add('sereneseasons:summer_crops', '/berries_and_cherries:.*grape.*sapling$/')
    e.add('sereneseasons:summer_crops', 'sunflowerdelight:sunflower_seeds')
    e.add('sereneseasons:summer_crops', 'vintagedelight:cucumber_seeds')
    e.add('sereneseasons:summer_crops', 'vintagedelight:ghost_pepper_seeds')
    e.add('sereneseasons:summer_crops', 'vintagedelight:oat_seeds')
    e.add('twilightforest:sapling', '/twilightforest:.*sapling/')
    yearRound('#twilightforest:sapling')
    yearRound('/ars_nouveau:.*_crop$/')
    yearRound('/ars_nouveau:.*_sapling$/')
    yearRound('/gtceu:.*_sapling$/')
    yearRound('/occultism:otherworld.*/')
})